#!/usr/bin/env python
from requests import Request, Session
import sys
import urllib

host = 'https://localhost:9801'
xtoken = '7sijC9zL-C3L7b7Xb0nvzQ'
query = ''

def configure():
    global query
    length = len(sys.argv)
    if length > 1:
        query = sys.argv[1]

def compileUrl():
    url = host
    if query != '':
        url = url + '?q=' + urllib.parse.quote(query)

    print(url)
    return url

configure()

session = Session()

headers = {
    'X-Token': xtoken,
}
res = session.get(compileUrl(), headers=headers, verify = './cert/awkwardCA.pem')
print(res.text)

